### ISSUE TITLE
Air temp and road temp swapped

### ISSUE THREAD

**Issue by johanssondavid** [endor-force/pytrafikverket#2]
On line 31-32 in pytrafikverket/pytrafikverket/trafikverket_weather.py air and road temp has been swapped.

**Comment by endor-force** [comment]
Sorry, must have missed notifcations on this repo..
Fixed in package 1.5.9 that is available in pypi now.
If you use home assistant the latest package version will be utilized when this PR is merged and released. https://github.com/home-assistant/home-assistant/pull/22139
