### ISSUE TITLE
Wind Speed Max

### ISSUE THREAD

**Issue by magma1447** [endor-force/pytrafikverket#6]
I am using pytrafikverket via [Home Assistant](https://github.com/home-assistant/core/tree/dev/homeassistant/components/trafikverket_weatherstation), but I am missing a measurement that's most relevant to me.

Is it possible to add **Measurement.Wind.ForceMax** to the mix? I played around with Trafikverket's API console and found that it existed there, with that name. I also tried to patch this library and the Home Assistant module, but without success. Not sure where I failed in the flow. I am not too experienced with Python.

**Comment by endor-force** [comment]
Hey there, if it is in the api we could certainly add it. 
It has to be added to both pytrafikverket library and home assistant in that order.

**Comment by magma1447** [comment]
That's what I tried, but failed with.

I made these two patches:
https://pastebin.com/LP5Nd8Br
https://pastebin.com/UtWGa5Pw

It's likely that I am missing something. My understanding for Python isn't too great, and even less how Home Assistant's modules works. It seemed simple though, besides the fact that it didn't work. :)

**Comment by endor-force** [comment]
https://github.com/home-assistant/home-assistant.io/pull/14256

**Comment by endor-force** [comment]
pytrafikverket is updated and pull requests created for home assistant docs and home assistant sensor code for trafikverket weatherstation

**Comment by endor-force** [comment]
It's now available in the 115 release of Home Assistant
